name: Playground

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  playground:
    runs-on: "ubuntu-latest"
    steps:

      - name: Playground
        run: |
          lsblk
          free
          sudo apt install zram-tools
          sudo systemctl restart zramswap
          sudo systemctl status zramswap.service
          sudo journalctl -xeu zramswap.service
          free