name: Playground

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  playground:
    runs-on: "ubuntu-latest"
    steps:

      - name: Playground
        run: |
          lsblk
          free
          sudo modprobe zram
          echo 8G | sudo tee /sys/block/zram0/disksize
          echo zstd | sudo tee /sys/block/zram0/comp_algorithm
          sudo mkswap /dev/zram0
          sudo swapon --priority 100 /dev/zram0
          free